### ISSUE TITLE
Pagina de Inicio - Login

### ISSUE THREAD

**Issue by sebasc91** [sebasc91/VOTAYA#2]
Pagina de autenticación del usuario

- [x] Diseño e implentación de vista Login @JSTORRES07
- [x] Diseño e implentación de vista Registro Usuario @JSTORRES07

**Comment by JSTORRES07** [comment]
[Imagenes Mockups.zip](https://github.com/sebasc91/VOTAYA/files/1432794/Imagenes.Mockups.zip)

**Comment by JSTORRES07** [comment]
[mockups.zip](https://github.com/sebasc91/VOTAYA/files/1433062/mockups.zip)
Se adjuntan Mockups de login, registro

**Comment by JSTORRES07** [comment]
[mockups.zip](https://github.com/sebasc91/VOTAYA/files/1433064/mockups.zip)

**Comment by JSTORRES07** [comment]
#2 Se carga mockups del login

**Comment by JSTORRES07** [comment]
#2 Se cargan imágenes del proyecto
