### ISSUE TITLE
Pagina de Votación

### ISSUE THREAD

**Issue by sebasc91** [sebasc91/VOTAYA#4]
Pagina de votación y elección de candidatos

- [x] Diseño e implementación de la pagina de votación @camilosandoval 
- [x] Diseño e implementación de vista de candidatos @camilosandoval 
- [x] Actualización del 1º sprint en la pagina web del proyecto @camilosandoval

**Comment by camilosandoval** [comment]
#4 Se realiza la codificación del modulo de votación

**Comment by camilosandoval** [comment]
#4 se agrega descripción y el botón de votar

**Comment by camilosandoval** [comment]
#4 Se modifica el código con el botos de votar y la descripción

**Comment by camilosandoval** [comment]
#4 Se implementan dos vistas de candidatos con su respectiva descripción y botones de votación

**Comment by camilosandoval** [comment]
#4 se agrega scrip con los tres módulos de candidatos

**Comment by camilosandoval** [comment]
#4 Se modifica el icono de los candidatos

**Comment by camilosandoval** [comment]
#4 Se modifica scrip con actualización de iconos.

**Comment by camilosandoval** [comment]
#4 Se agregan tres candidatos mas para un total de seis.

**Comment by camilosandoval** [comment]
4#  actualización de script para un total de seis candidatos

**Comment by camilosandoval** [comment]
#4 Modificación de icono de los candidatos.

**Comment by camilosandoval** [comment]
#4 modificación del icono de los candidatos

**Comment by camilosandoval** [comment]
#4 Scirp con el cambio de icono.

**Comment by camilosandoval** [comment]
#4 actualización final, alineación de texto.

**Comment by camilosandoval** [comment]
#4 Ultimo script modulo de votación

**Comment by camilosandoval** [comment]
#4 se actualiza pagina WEB
