### ISSUE TITLE
Vista Reportes Elecciones

### ISSUE THREAD

**Issue by sebasc91** [sebasc91/VOTAYA#5]
Implementar la vista de reportes de las elecciones

- [x] Vista de reporte de resultado candidatos @camilosandoval 
- [x] Vista de reporte de conteo de votos vistas parciales @camilosandoval 
- [x] Vista de reporte de ganador y conteo de votos @camilosandoval 
- [x] Actualización del gestor de contenido (Pagina Web) según retroalimentación del sprint 1 @camilosandoval

**Comment by camilosandoval** [comment]
#5 Se realiza vista de resultado de los candidatos

**Comment by camilosandoval** [comment]
#5 Se agrega script de reporte

**Comment by camilosandoval** [comment]
#5 Se modifica iconos de los candidatos

**Comment by camilosandoval** [comment]
#5 Script modificación de imagen

**Comment by camilosandoval** [comment]
#5 Se agregan nombres a los candidatos y Cantidad de votos aleatoria

**Comment by camilosandoval** [comment]
#5 Script modiciación de nombres a los candidatos y Cantidad de votos aleatoria

**Comment by camilosandoval** [comment]
#5 implementación de ganador en el reporte y botón para generar archivo en PDF

**Comment by camilosandoval** [comment]
#5 Script con actualización de ganador y botón PDF

**Comment by camilosandoval** [comment]
#5 implementación de ganador en el reporte y botón para generar archivo en PDF

**Comment by camilosandoval** [comment]
#5 Actualización de documentos en el gestor documental
