### ISSUE TITLE
Vista Principal del Sistema

### ISSUE THREAD

**Issue by sebasc91** [sebasc91/VOTAYA#7]
Implementar la vista principal del sistema de votación y sus respectivos menús de navegación

- [x] Implementar vista principal @JSTORRES07 
- [x] Implementar menús de navegación @JSTORRES07

**Comment by JSTORRES07** [comment]
#7  subo código e imagen de vista principal del sistema.

**Comment by JSTORRES07** [comment]
#7 subo codigo e imagen de vistas de menus
