### ISSUE TITLE
Integración de vistas

### ISSUE THREAD

**Issue by sebasc91** [sebasc91/VOTAYA#8]
Integración y corrección de vistas

- [x] Realizar la integración de las vistas realizadas @JSTORRES07 
- [x] Implementar recuperar contraseña @JSTORRES07 
- [x] Corrección de vistas, según las retroalimentaciones @JSTORRES07

**Comment by JSTORRES07** [comment]
#8 Se realiza integración de las vistas trabajadas
![modulo de contacto](https://user-images.githubusercontent.com/33036533/32977936-9d3b15d4-cc05-11e7-9b2e-6108efee8582.jpg)
![modulo de informacion](https://user-images.githubusercontent.com/33036533/32977937-9d4f6228-cc05-11e7-949e-41abc8fdf275.jpg)
![modulo de reportes](https://user-images.githubusercontent.com/33036533/32977938-9d6581d4-cc05-11e7-8fd4-f781f2868c8a.jpg)
![modulo de votacion](https://user-images.githubusercontent.com/33036533/32977939-9d7d562e-cc05-11e7-9a02-71fc52ea98df.jpg)
![registro](https://user-images.githubusercontent.com/33036533/32977940-9d939330-cc05-11e7-809c-b31f723871db.jpg)
![inicio](https://user-images.githubusercontent.com/33036533/32977941-9db1483a-cc05-11e7-8db1-0439bcc45a08.jpg)
![login](https://user-images.githubusercontent.com/33036533/32977942-9dc8ebb6-cc05-11e7-83f9-d52dbf2a4c71.jpg)

**Comment by JSTORRES07** [comment]
#8 se realiza modulo de recordar contraseña
![registro](https://user-images.githubusercontent.com/33036533/32977966-46091706-cc06-11e7-81a0-02727599f43b.jpg)

**Comment by JSTORRES07** [comment]
#8 Se cargan vistas corregidas
![inicio](https://user-images.githubusercontent.com/33036533/32977972-6c0cb0f2-cc06-11e7-9372-3dc2b75b4736.jpg)
![login](https://user-images.githubusercontent.com/33036533/32977973-6c2140b2-cc06-11e7-84ef-8cd5d02a7943.jpg)
![modulo de contacto](https://user-images.githubusercontent.com/33036533/32977974-6c36fc72-cc06-11e7-8eb9-bbe4c3021795.jpg)
![modulo de informacion](https://user-images.githubusercontent.com/33036533/32977975-6c4e2096-cc06-11e7-8c11-d9e063facdf1.jpg)
![modulo de reportes](https://user-images.githubusercontent.com/33036533/32977976-6c6826c6-cc06-11e7-8953-e1afb9570c4b.jpg)
![modulo de votacion](https://user-images.githubusercontent.com/33036533/32977977-6c8be5ca-cc06-11e7-990c-bb7f5226ec78.jpg)
![registro](https://user-images.githubusercontent.com/33036533/32977978-6ce35e90-cc06-11e7-890d-c5de473cca10.jpg)
