### ISSUE TITLE
Realizar correcciones según retroalimentaciones

### ISSUE THREAD

**Issue by sebasc91** [sebasc91/VOTAYA#9]
Correcciones de acuerdo a las retroalimentaciones realizadas en cada sprint

- [x] Correcciones sobre las vistas implementadas @camilosandoval 
- [x] Actualización de la página WEB del proyecto @camilosandoval 
- [x] Corrección del gestor de contenido del proyecto según retroalimentaciones realizadas @camilosandoval

**Comment by camilosandoval** [comment]
#9 Se realizan modificaciones a las vistas de candidatos y reportes
